/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 20 10:30:49 GMT 2026
 */

package org.spotifumtp37.model.playlist;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.Album;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.subscription.PremiumTop;
import org.spotifumtp37.model.subscription.SubscriptionPlan;
import org.spotifumtp37.model.user.History;
import org.spotifumtp37.model.user.User;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Playlist_ESTest extends Playlist_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song();
      linkedList0.push(song0);
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist(user0, "W[LykXr~]WQD}$='N)", "", 491, "", linkedList0);
      playlist0.previous(user0);
      assertEquals(491, playlist0.getNumberOfFollowers());
      assertEquals("W[LykXr~]WQD}$='N)", playlist0.getPlaylistName());
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "", "", 0, "", linkedList0);
      Playlist playlist1 = new Playlist(playlist0);
      playlist0.setNumberOfFollowers(125);
      boolean boolean0 = playlist1.equals(playlist0);
      assertEquals(125, playlist0.getNumberOfFollowers());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "dd2g>w,+\"pi%ww$", "public", 125, "public", (List<Song>) null);
      boolean boolean0 = playlist0.isPublic();
      assertEquals("public", playlist0.getPlaylistDescription());
      assertTrue(boolean0);
      assertEquals(125, playlist0.getNumberOfFollowers());
      assertEquals("dd2g>w,+\"pi%ww$", playlist0.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "gdqoh_8ku)`'", (String) null, 136, "private", linkedList0);
      boolean boolean0 = playlist0.isPrivate();
      assertEquals(136, playlist0.getNumberOfFollowers());
      assertEquals("gdqoh_8ku)`'", playlist0.getPlaylistName());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "}yX\b%#1+p4g", (String) null, (-1898), (String) null, linkedList0);
      String string0 = playlist0.getStatus();
      assertNull(string0);
      assertEquals((-1898), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ";$Ssx6E<Q.RtO@@8", "[@?q;s@", (-4393), "", list0);
      String string0 = playlist0.getStatus();
      assertEquals(";$Ssx6E<Q.RtO@@8", playlist0.getPlaylistName());
      assertEquals("[@?q;s@", playlist0.getPlaylistDescription());
      assertEquals("", string0);
      assertEquals((-4393), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("}FVZ2|q<u ", (String) null, "HYd:*<1s@", premiumTop0, "/KEQXwc};>_k", 1259.405780474454, linkedList0);
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, (String) null, "~{3IWmgA|", 1, "~{3IWmgA|", list0);
      String string0 = playlist0.getPlaylistName();
      assertEquals(1, playlist0.getNumberOfFollowers());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "", "", 0, ", musicalnotes='", linkedList0);
      String string0 = playlist0.getPlaylistName();
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals("", string0);
      assertEquals(0, playlist0.getNumberOfFollowers());
      assertEquals(", musicalnotes='", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylistWithinTime(hashMap0, 2646);
      Playlist playlist0 = new Playlist(user0, "P8p*PRJE=9~O1Pb\u0001.C", (String) null, 2646, "dx}[iuz@w8z ll", list0);
      String string0 = playlist0.getPlaylistDescription();
      assertNull(string0);
      assertEquals(2646, playlist0.getNumberOfFollowers());
      assertEquals("dx}[iuz@w8z ll", playlist0.getStatus());
      assertEquals("P8p*PRJE=9~O1Pb\u0001.C", playlist0.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User(", genre='", "", ", genre='", premiumTop0, ", genre='", 0.0, linkedList0);
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      LinkedList<Song> linkedList1 = new LinkedList<Song>(list0);
      Playlist playlist0 = new Playlist(user0, ", genre='", "", 1415, ", genre='", linkedList1);
      String string0 = playlist0.getPlaylistDescription();
      assertEquals(", genre='", playlist0.getStatus());
      assertEquals(", genre='", playlist0.getPlaylistName());
      assertEquals("", string0);
      assertEquals(1415, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, ">oeUqDHkh$,W", ">oeUqDHkh$,W", 0, ">oeUqDHkh$,W", linkedList0);
      int int0 = playlist0.getNumberOfFollowers();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "This song is already in the playlist.", "^7&zer=ky,8io4+w", (-144), "", linkedList0);
      int int0 = playlist0.getNumberOfFollowers();
      assertEquals("^7&zer=ky,8io4+w", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getStatus());
      assertEquals("This song is already in the playlist.", playlist0.getPlaylistName());
      assertEquals((-144), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ";$Ssx6E<Q.RtO@@8", "[@?q;s@", (-4393), "", list0);
      Song song0 = new Song((String) null, "", (String) null, ";$Ssx6E<Q.RtO@@8", "", ";$Ssx6E<Q.RtO@@8", (-4393));
      song0.incrementTimesPlayed();
      playlist0.setCurrentSong(song0);
      playlist0.getCurrentSong();
      assertEquals(";$Ssx6E<Q.RtO@@8", playlist0.getPlaylistName());
      assertEquals("[@?q;s@", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getStatus());
      assertEquals((-4393), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      User user0 = new User();
      Song song0 = new Song("org.spotifumtp37.model.album.Song", "}yX\b%#1+p4g", "", "qJ|2LZcDcbO<^", "org.spotifumtp37.model.album.Song", (String) null, 0);
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist(user0, "}yX\b%#1+p4g", (String) null, (-1898), (String) null, linkedList0);
      Song song1 = playlist0.getCurrentSong();
      assertNotNull(song1);
      assertEquals((-1898), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      User user0 = new User();
      Song song0 = new Song("U&*UB1ahpXO+lxlb?", "U&*UB1ahpXO+lxlb?", "", "", "org.spotifumtp37.model.user.History", "org.spotifumtp37.model.user.History", 278);
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist(user0, "", "org.spotifumtp37.model.user.History", 125, "(c9?BEQR-5KLX>}`g", linkedList0);
      Song song1 = playlist0.getCurrentSong();
      assertEquals("(c9?BEQR-5KLX>}`g", playlist0.getStatus());
      assertEquals("org.spotifumtp37.model.user.History", playlist0.getPlaylistDescription());
      assertEquals(125, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistName());
      assertNotNull(song1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, (String) null, "&2lus(g]#u4``aj", 280, "", linkedList0);
      playlist0.getCreator();
      assertEquals(280, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getStatus());
      assertEquals("&2lus(g]#u4``aj", playlist0.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "", "org.spotifumtp37.model.user.History", 125, "(c9?BEQR-5KLX>}`g", linkedList0);
      playlist0.getCreator();
      assertEquals("(c9?BEQR-5KLX>}`g", playlist0.getStatus());
      assertEquals("org.spotifumtp37.model.user.History", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getPlaylistName());
      assertEquals(125, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      PremiumBase premiumBase0 = new PremiumBase();
      User user0 = new User();
      List<History> list0 = user0.getHistory();
      User user1 = new User("z14Uc#{h%c@DvN/-", "SB", "", premiumBase0, "kAO[CaED:K", (-247.048298), list0);
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user1, "SB", "z14Uc#{h%c@DvN/-", 3374, "", linkedList0);
      playlist0.getCreator();
      assertEquals(3374, playlist0.getNumberOfFollowers());
      assertEquals("z14Uc#{h%c@DvN/-", playlist0.getPlaylistDescription());
      assertEquals("SB", playlist0.getPlaylistName());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "private", "%Jx6j8e\"VA", (-1), "private", (List<Song>) null);
      Playlist playlist1 = playlist0.clone();
      assertEquals("private", playlist1.getPlaylistName());
      assertTrue(playlist1.equals((Object)playlist0));
      assertEquals("%Jx6j8e\"VA", playlist1.getPlaylistDescription());
      assertTrue(playlist1.isPrivate());
      assertEquals((-1), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, "", "", 0, "null", list0);
      Playlist playlist1 = playlist0.clone();
      assertEquals("null", playlist1.getStatus());
      assertEquals("", playlist1.getPlaylistDescription());
      assertEquals("", playlist1.getPlaylistName());
      assertEquals(0, playlist0.getNumberOfFollowers());
      assertTrue(playlist1.equals((Object)playlist0));
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "yo-)xp", "yo-)xp", 125, "yo-)xp", linkedList0);
      Playlist playlist1 = playlist0.clone();
      assertTrue(playlist1.equals((Object)playlist0));
      assertEquals(125, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "", "", 0, "", linkedList0);
      linkedList0.add((Song) null);
      // Undeclared exception!
      try { 
        playlist0.setSongs(linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "Tf>iS@5", "Tf>iS@5", 3935, "Tf>iS@5", linkedList0);
      // Undeclared exception!
      try { 
        playlist0.deleteSong((Song) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot delete a null song from the playlist.
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "E\"lLuY'1*", "E\"lLuY'1*", 106, "E\"lLuY'1*", linkedList0);
      // Undeclared exception!
      try { 
        playlist0.addSong((Song) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot add a null song to the playlist.
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      linkedList0.add((Song) null);
      Playlist playlist0 = null;
      try {
        playlist0 = new Playlist(user0, "Tf>iS@5", "Tf>iS@5", 2, "Tf>iS@5", linkedList0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Playlist playlist0 = null;
      try {
        playlist0 = new Playlist((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song();
      linkedList0.add(song0);
      linkedList0.add(song0);
      PremiumBase premiumBase0 = new PremiumBase();
      user0.setSubscriptionPlan(premiumBase0);
      Playlist playlist0 = new Playlist(user0, (String) null, (String) null, (-1502), (String) null, linkedList0);
      playlist0.deleteSong(song0);
      assertEquals((-1502), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      playlist0.deleteSong(song0);
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getStatus());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      // Undeclared exception!
      try { 
        playlist0.deleteSong(song0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // This song is not in the playlist.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = new User();
      List<History> list0 = user0.getHistory();
      User user1 = new User("&h.fh%Q.R6{@:", "oe&8", "&h.fh%Q.R6{@:", (SubscriptionPlan) null, ", videoLink='", (-1.0), list0);
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list1 = user1.createTopGenrePlaylistWithinTime(hashMap0, (-1));
      Playlist playlist0 = new Playlist(user1, "oe&8", ", videoLink='", (-1), "&h.fh%Q.R6{@:", list1);
      Song song0 = new Song();
      // Undeclared exception!
      try { 
        playlist0.deleteSong(song0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Playlist creator or subscription plan is not properly initialized.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      try { 
        playlist0.deleteSong(song0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Your subscription does not allow deleting songs from the playlist.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Playlist playlist0 = new Playlist((User) null, "9FztQ5+%.X#Vx", "9FztQ5+%.X#Vx", (-1032), "9FztQ5+%.X#Vx", (List<Song>) null);
      Song song0 = new Song("Playlist{creator: {", "HME%FXuO,K", "Q\u0003!;u(Kcm\"", "1ewmi$e[", "9FztQ5+%.X#Vx", "HME%FXuO,K", (-1032));
      // Undeclared exception!
      try { 
        playlist0.deleteSong(song0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Playlist creator or subscription plan is not properly initialized.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      User user0 = new User();
      PremiumTop premiumTop0 = new PremiumTop();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "qJ|2LZcDcbO<^", "]F", 31, "qJ|2LZcDcbO<^", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      // Undeclared exception!
      try { 
        playlist0.addSong(song0);
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // This song is already in the playlist.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, ">oeUqDHkh$,W", ">oeUqDHkh$,W", 0, ">oeUqDHkh$,W", linkedList0);
      Song song0 = new Song();
      try { 
        playlist0.addSong(song0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Your subscription does not allow adding songs to the playlist.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User((String) null, "dB@o7PU;1hr+j-:'", "@f]|", (SubscriptionPlan) null, "Playlist creator or subscription plan is not properly initialized.", (-1006.48588756), linkedList0);
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, "L6@m(^L%Ju>rqy{w)>w", "Playlist creator or subscription plan is not properly initialized.", 125, "@f]|", list0);
      Song song0 = new Song("?*dmDRpWyMF", (String) null, "7dn+^", "C!l}12m{", "Playlist creator or subscription plan is not properly initialized.", "7dn+^", 125);
      // Undeclared exception!
      try { 
        playlist0.addSong(song0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Playlist creator or subscription plan is not properly initialized.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "org.spotifumtp37.model.subscription.FreePlan", "org.spotifumtp37.model.album.ExplicitSong", (-1), "^7&zer=ky,8io4+w", linkedList0);
      Song song0 = new Song();
      // Undeclared exception!
      try { 
        playlist0.addSong(song0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Playlist creator or subscription plan is not properly initialized.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      User user0 = new User();
      PremiumTop premiumTop0 = new PremiumTop();
      User user1 = new User();
      user1.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user1, "null", "Album{title='", 2147483645, "#\"8L<i:", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      try { 
        playlist0.previous(user0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Your subscription does not allow going back in the playlist.
         //
         verifyException("org.spotifumtp37.model.playlist.Playlist", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      User user0 = new User();
      Song song0 = new Song();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist(user0, "E\"lLuY'1*", "E\"lLuY'1*", 106, "E\"lLuY'1*", linkedList0);
      List<History> list0 = user0.getHistory();
      User user1 = new User("Your subscription does not allow going back in the playlist.", "} ', playlistName='", "vloW)kQ+&^'yUqCi)Yp", (SubscriptionPlan) null, "zD", (-1.0), list0);
      playlist0.previous(user1);
      assertEquals(106, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      playlist0.previous((User) null);
      assertEquals("", playlist0.getStatus());
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      playlist0.previous(user0);
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      song0.setPublisher((String) null);
      playlist0.addSong(song0);
      playlist0.next(user0);
      playlist0.nextShuffle();
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      song0.setPublisher((String) null);
      playlist0.addSong(song0);
      // Undeclared exception!
      playlist0.nextShuffle();
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      playlist0.nextShuffle();
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      playlist0.nextShuffle();
      assertEquals("", playlist0.getStatus());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song();
      linkedList0.add(song0);
      linkedList0.add(song0);
      Random.setNextRandom(1);
      Playlist playlist0 = new Playlist(user0, (String) null, (String) null, (-1526), (String) null, linkedList0);
      playlist0.next(user0);
      assertEquals((-1526), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song();
      linkedList0.add(song0);
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist(user0, (String) null, (String) null, (-1526), (String) null, linkedList0);
      // Undeclared exception!
      playlist0.next(user0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "", "^7&zer=ky,8io4+w", 2147483645, "^7&zer=ky,8io4+w", (List<Song>) null);
      User user1 = new User();
      Song song0 = new Song();
      playlist0.addSong(song0);
      playlist0.next(user1);
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistName());
      assertEquals("^7&zer=ky,8io4+w", playlist0.getStatus());
      assertEquals("^7&zer=ky,8io4+w", playlist0.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "Hdqoh_8Ku)`'", "Hdqoh_8Ku)`'", 75, "Hdqoh_8Ku)`'", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      List<History> list0 = user0.getHistory();
      User user1 = new User(", status='", ", status='", "private", (SubscriptionPlan) null, ", email='", 75, list0);
      playlist0.next(user1);
      assertEquals(75, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song();
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist((User) null, (String) null, (String) null, 561, (String) null, linkedList0);
      playlist0.next((User) null);
      assertEquals(561, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      playlist0.next(user0);
      assertEquals("", playlist0.getStatus());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      playlist0.play(user0);
      assertEquals(102.49999999999999, user0.getPontos(), 0.01);
      
      playlist0.addSong(song0);
      playlist0.deleteSong(song0);
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      playlist0.play((User) null);
      assertEquals("", playlist0.getStatus());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "", "", 0, "", linkedList0);
      playlist0.play(user0);
      assertEquals(0, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      User user0 = new User();
      Song song0 = new Song();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist(user0, "gdqoh_8ku)`'", (String) null, 136, "private", linkedList0);
      playlist0.setSongs(linkedList0);
      assertEquals(136, playlist0.getNumberOfFollowers());
      assertTrue(playlist0.isPrivate());
      assertEquals("gdqoh_8ku)`'", playlist0.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "1IFb3q<oNlR,uct", "org.spotifumtp37.model.subscription.freeplan", 2147483645, "1IFb3q<oNlR,uct", (List<Song>) null);
      playlist0.setSongs((List<Song>) null);
      assertEquals("org.spotifumtp37.model.subscription.freeplan", playlist0.getPlaylistDescription());
      assertEquals("1IFb3q<oNlR,uct", playlist0.getPlaylistName());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("1IFb3q<oNlR,uct", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "org.spotifumtp37.model.subscription.FreePlan", "org.spotifumtp37.model.subscription.FreePlan", (-1), "^7&zer=ky,8io4+w", linkedList0);
      Song song0 = new Song("^7&zer=ky,8io4+w", ":CZ+o?Z(#>oQwxBp\"", "org.spotifumtp37.model.subscription.FreePlan", "4>kmo\u0005%3,D}.", "4>kmo\u0005%3,D}.", "dH_#n@acwoO+u>~", (-1));
      linkedList0.add(song0);
      playlist0.setSongs(linkedList0);
      List<Song> list0 = playlist0.getSongs();
      assertTrue(list0.contains(song0));
      assertEquals("^7&zer=ky,8io4+w", playlist0.getStatus());
      assertEquals("org.spotifumtp37.model.subscription.FreePlan", playlist0.getPlaylistName());
      assertEquals("org.spotifumtp37.model.subscription.FreePlan", playlist0.getPlaylistDescription());
      assertEquals((-1), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "private", "%Jx6j8e\"VA", (-1), "private", (List<Song>) null);
      playlist0.getSongs();
      assertEquals("%Jx6j8e\"VA", playlist0.getPlaylistDescription());
      assertEquals("private", playlist0.getPlaylistName());
      assertEquals((-1), playlist0.getNumberOfFollowers());
      assertEquals("private", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      User user0 = new User();
      Song song0 = new Song("U&*UB1ahpXO+lxlb?", "U&*UB1ahpXO+lxlb?", "", "", "org.spotifumtp37.model.user.History", "org.spotifumtp37.model.user.History", 278);
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      linkedList0.add(song0);
      Playlist playlist0 = new Playlist(user0, "", "org.spotifumtp37.model.user.History", 125, "(c9?BEQR-5KLX>}`g", linkedList0);
      playlist0.toString();
      assertEquals("org.spotifumtp37.model.user.History", playlist0.getPlaylistDescription());
      assertEquals("(c9?BEQR-5KLX>}`g", playlist0.getStatus());
      assertEquals(125, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ", password='", ", password='", 31, "", list0);
      playlist0.toString();
      assertEquals(", password='", playlist0.getPlaylistName());
      assertEquals(31, playlist0.getNumberOfFollowers());
      assertEquals(", password='", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "This song is not in the playlist.", "This song is not in the playlist.", 1129, ".r`uxrf2=", linkedList0);
      String string0 = playlist0.toString();
      assertEquals("Playlist{creator: {null} ', playlistName='This song is not in the playlist.', playlistDescription='This song is not in the playlist.', numberOfFollowers=1129, status='.r`uxrf2=', songs=[]}, currentsong: {null}", string0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "_+k-np", "_+k-np", 619, "_+k-np", linkedList0);
      Playlist playlist1 = new Playlist(playlist0);
      assertTrue(playlist1.equals((Object)playlist0));
      
      Song song0 = new Song();
      playlist1.setCurrentSong(song0);
      boolean boolean0 = playlist0.equals(playlist1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "_+k-np", "_+k-np", 619, "_+k-np", linkedList0);
      Playlist playlist1 = new Playlist(playlist0);
      assertTrue(playlist1.equals((Object)playlist0));
      
      playlist1.setStatus("[$N=~&r`=+3bC3");
      boolean boolean0 = playlist0.equals(playlist1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "_+k-np", "_+k-np", 619, "_+k-np", linkedList0);
      Playlist playlist1 = new Playlist(playlist0);
      boolean boolean0 = playlist0.equals(playlist1);
      assertEquals(619, playlist0.getNumberOfFollowers());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, " C", " C", 0, " C", linkedList0);
      Playlist playlist1 = new Playlist(playlist0);
      assertTrue(playlist1.equals((Object)playlist0));
      
      playlist0.setPlaylistDescription("@,=2 &wBw");
      boolean boolean0 = playlist0.equals(playlist1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "_+k-np", "_+k-np", 619, "_+k-np", linkedList0);
      Playlist playlist1 = new Playlist(playlist0);
      assertTrue(playlist1.equals((Object)playlist0));
      
      playlist1.setPlaylistName("O-!GlGZ'%oym");
      boolean boolean0 = playlist0.equals(playlist1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "W[LykXr~]WQD}$='N)", "", 491, "", linkedList0);
      boolean boolean0 = playlist0.equals(premiumTop0);
      assertFalse(boolean0);
      assertEquals("W[LykXr~]WQD}$='N)", playlist0.getPlaylistName());
      assertEquals("", playlist0.getPlaylistDescription());
      assertEquals(491, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "yo-)xp", "yo-)xp", (-3633), "yo-)xp", linkedList0);
      boolean boolean0 = playlist0.equals((Object) null);
      assertEquals((-3633), playlist0.getNumberOfFollowers());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, ".R`uXrF2=", ".R`uXrF2=", 654, ".R`uXrF2=", linkedList0);
      boolean boolean0 = playlist0.equals(playlist0);
      assertEquals(654, playlist0.getNumberOfFollowers());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "Ths song is not int{e playlist.", "Ths song is not int{e playlist.", (-17), "Ths song is not int{e playlist.", linkedList0);
      Playlist playlist1 = new Playlist(user0, "Ths song is not int{e playlist.", "Ths song is not int{e playlist.", (-1), "Ths song is not int{e playlist.", linkedList0);
      boolean boolean0 = playlist1.equals(playlist0);
      assertFalse(playlist0.equals((Object)playlist1));
      assertEquals((-1), playlist1.getNumberOfFollowers());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      User user0 = new User();
      PremiumTop premiumTop0 = new PremiumTop();
      user0.updatePremiumTop(premiumTop0);
      Playlist playlist0 = new Playlist(user0, "qJ|2LZcDcbO<^", "]F", 31, "c}3\"JW_xv ", (List<Song>) null);
      Song song0 = new Song();
      playlist0.addSong(song0);
      Playlist playlist1 = new Playlist(playlist0);
      assertEquals("c}3\"JW_xv ", playlist1.getStatus());
      assertTrue(playlist1.equals((Object)playlist0));
      assertEquals(31, playlist0.getNumberOfFollowers());
      assertEquals("qJ|2LZcDcbO<^", playlist1.getPlaylistName());
      assertEquals("]F", playlist1.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ", password='", ", password='", 31, "", list0);
      String string0 = playlist0.getPlaylistDescription();
      assertEquals(", password='", string0);
      assertEquals("", playlist0.getStatus());
      assertEquals(31, playlist0.getNumberOfFollowers());
      assertEquals(", password='", playlist0.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ", password='", ", password='", 31, "", list0);
      playlist0.setCreatorUsername(user0);
      assertEquals(", password='", playlist0.getPlaylistDescription());
      assertEquals("", playlist0.getStatus());
      assertEquals(", password='", playlist0.getPlaylistName());
      assertEquals(31, playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ", password='", ", password='", 31, "", list0);
      int int0 = playlist0.getNumberOfFollowers();
      assertEquals(", password='", playlist0.getPlaylistDescription());
      assertEquals(31, int0);
      assertEquals(", password='", playlist0.getPlaylistName());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, "l+]<0}ip1ogcr", "6ILj+op,A", (-1), "public", list0);
      Playlist playlist1 = playlist0.clone();
      assertTrue(playlist1.equals((Object)playlist0));
      assertEquals("public", playlist1.getStatus());
      assertEquals("l+]<0}ip1ogcr", playlist1.getPlaylistName());
      assertEquals((-1), playlist1.getNumberOfFollowers());
      assertEquals("6ILj+op,A", playlist1.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      String string0 = playlist0.getPlaylistName();
      assertEquals("", playlist0.getStatus());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("c}3\"JW_xv ", string0);
      assertEquals("", playlist0.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ";$Ssx6E<Q.RtO@@8", "[@?q;s@", (-4393), "", list0);
      playlist0.getCreator();
      assertEquals("", playlist0.getStatus());
      assertEquals((-4393), playlist0.getNumberOfFollowers());
      assertEquals("[@?q;s@", playlist0.getPlaylistDescription());
      assertEquals(";$Ssx6E<Q.RtO@@8", playlist0.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "c}3\"JW_xv ", "", 2147483645, "", (List<Song>) null);
      boolean boolean0 = playlist0.isPublic();
      assertFalse(boolean0);
      assertEquals("", playlist0.getStatus());
      assertEquals("c}3\"JW_xv ", playlist0.getPlaylistName());
      assertEquals(2147483645, playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, ";$Ssx6E<Q.RtO@@8", "[@?q;s@", (-4393), "", list0);
      playlist0.getCurrentSong();
      assertEquals(";$Ssx6E<Q.RtO@@8", playlist0.getPlaylistName());
      assertEquals("[@?q;s@", playlist0.getPlaylistDescription());
      assertEquals((-4393), playlist0.getNumberOfFollowers());
      assertEquals("", playlist0.getStatus());
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      LinkedList<History> linkedList1 = new LinkedList<History>();
      User user0 = new User((String) null, (String) null, "Playlist creator or subscription plan is not properly initialized.", (SubscriptionPlan) null, "iy'z3n|$nle6b", 0.0, linkedList1);
      Playlist playlist0 = new Playlist(user0, "X\"a><4B_", ", releaseYear=", (-3254), (String) null, linkedList0);
      playlist0.isPrivate();
      assertEquals("X\"a><4B_", playlist0.getPlaylistName());
      assertEquals(", releaseYear=", playlist0.getPlaylistDescription());
      assertEquals((-3254), playlist0.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "org.spotifumtp37.model.subscription.FreePlan", "org.spotifumtp37.model.subscription.FreePlan", (-1), "^7&zer=ky,8io4+w", linkedList0);
      String string0 = playlist0.getStatus();
      assertEquals((-1), playlist0.getNumberOfFollowers());
      assertEquals("^7&zer=ky,8io4+w", string0);
      assertEquals("org.spotifumtp37.model.subscription.FreePlan", playlist0.getPlaylistName());
      assertEquals("org.spotifumtp37.model.subscription.FreePlan", playlist0.getPlaylistDescription());
  }
}
