/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 20 10:23:59 GMT 2026
 */

package org.spotifumtp37.model.album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.subscription.FreePlan;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.subscription.PremiumTop;
import org.spotifumtp37.model.user.History;
import org.spotifumtp37.model.user.User;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Album_ESTest extends Album_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("-", ", email='", "-", "-", "OR0*8 E(\";y JUJ4U8", 3186, true, true, ", email='");
      album0.setCurrentSong();
      album0.addSong("8w9'|1]:]", "8w9'|1]:]", "", "8w9'|1]:]", ", email='", 3186, true, false, "-");
      User user0 = new User();
      PremiumTop premiumTop0 = new PremiumTop();
      user0.updatePremiumTop(premiumTop0);
      album0.next(user0);
      album0.nextShuffle();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong(", genre='", ", releaseYear=", "5O;8hms:iO", "=_:x*7&O", "M", 125, false, true, "");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong("#t\"", "", "/H?\"Q.I&e-F$[MYS", "#t\"", "/H?\"Q.I&e-F$[MYS", 0, false, false, "#t\"");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song duration must be positive.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Album album0 = new Album();
      Album album1 = new Album(album0);
      assertEquals(0, album1.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("^081vK2xj'k,02", "X[", "X[", "X[", "org.spotifumtp37.model.subscription.FreePlan", 23, false, false, "org.spotifumtp37.model.subscription.FreePlan");
      PremiumBase premiumBase0 = new PremiumBase();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("org.spotifumtp37.model.subscription.FreePlan", "X[", "X[", premiumBase0, "X[", 23, linkedList0);
      album0.previous(user0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("multimedia=", "multimedia=", (String) null, "%0i G]J}|otT", "multimedia=", 3289, true, true, ", publisher='");
      int int0 = album0.getTotalDuration();
      assertEquals(3289, int0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song("+|fkY[*+7j}),$*", "+|fkY[*+7j}),$*", ", artist='", ", artist='", "$!X#", "", (-2490));
      linkedList0.add(song0);
      Album album0 = new Album("multimedia=", "multimedia=", (-2490), "multimedia=", linkedList0);
      album0.getTotalDuration();
      assertEquals((-2490), album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Album album0 = new Album((String) null, (String) null, (-2129), "b)|nE`", list0);
      String string0 = album0.getTitle();
      assertEquals((-2129), album0.getReleaseYear());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      User user0 = new User();
      List<Song> list0 = user0.createTopGenrePlaylist((Map<String, Album>) null);
      Album album0 = new Album("'{{~{6'=rN", "'{{~{6'=rN", 6036, "", list0);
      String string0 = album0.getTitle();
      assertEquals("'{{~{6'=rN", album0.getArtist());
      assertEquals("", album0.getGenre());
      assertEquals("'{{~{6'=rN", string0);
      assertEquals(6036, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("TCVB", "?", "\u0004DAnIfcJ[@Vil", "User{name='", ", genre='", 21, true, true, "Jh~8a})[&29J");
      album0.getSongs();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongsCopy();
      Album album1 = new Album("m/usP|UF", "", 554, ", currentSong=", list0);
      int int0 = album1.getReleaseYear();
      assertEquals("", album1.getArtist());
      assertEquals(0, album0.getReleaseYear());
      assertEquals("m/usP|UF", album1.getTitle());
      assertEquals(", currentSong=", album1.getGenre());
      assertEquals(554, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylistWithinTime(hashMap0, (-2401));
      Album album0 = new Album("", ", subscription plan=", (-2244), "Album{title='", list0);
      int int0 = album0.getReleaseYear();
      assertEquals("Album{title='", album0.getGenre());
      assertEquals(", subscription plan=", album0.getArtist());
      assertEquals("", album0.getTitle());
      assertEquals((-2244), int0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongsCopy();
      Album album1 = new Album(" sBE_YHx6qEQs8o_", ", currentSong=", 304, (String) null, list0);
      String string0 = album1.getGenre();
      assertEquals(" sBE_YHx6qEQs8o_", album1.getTitle());
      assertEquals(", currentSong=", album1.getArtist());
      assertEquals(0, album0.getReleaseYear());
      assertNull(string0);
      assertEquals(304, album1.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Album album0 = new Album();
      album0.getGenre();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Album album0 = new Album();
      album0.setCurrentSong((Song) null);
      album0.getCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      album0.play(user0);
      album0.getCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Album album0 = new Album();
      Song song0 = new Song("\u0007XP-T_t`", "multimedia=", "8x9qe", "org.spotifumtp37.model.user.History", "_,f?d.", "org.spotifumtp37.model.user.History", 0);
      song0.setTimesPlayed((-1672));
      album0.setCurrentSong(song0);
      album0.getCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      PremiumTop premiumTop0 = new PremiumTop();
      user0.updatePremiumTop(premiumTop0);
      album0.addSong("*", "Song duration must be positive.", "Song duration must be positive.", "*", (String) null, 39, true, false, "UH(!&");
      album0.next(user0);
      Song song0 = album0.getCurrentSong();
      assertEquals("Song duration must be positive.", song0.getPublisher());
      assertEquals("*", song0.getMusicalNotes());
      assertEquals("Song duration must be positive.", song0.getLyrics());
      assertEquals("*", song0.getName());
      assertEquals(0, album0.getReleaseYear());
      assertEquals(39, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Album album0 = new Album();
      album0.setArtist((String) null);
      album0.getArtist();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      FreePlan freePlan0 = new FreePlan();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User((String) null, (String) null, (String) null, freePlan0, "", 1628.9862743524, linkedList0);
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylist(hashMap0);
      Album album0 = new Album((String) null, "D?q?tGd", (-1255), "D?q?tGd", list0);
      String string0 = album0.getArtist();
      assertEquals((-1255), album0.getReleaseYear());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("*", "'g]6", "'g]6", "Your subscription does not allow going back in the playlist.", "*", 2, false, false, (String) null);
      album0.deleteSong("*");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      User user0 = new User();
      List<Song> list0 = user0.createTopGenrePlaylist((Map<String, Album>) null);
      Album album0 = new Album("'{{~{6'=rN", "'{{~{6'=rN", 6036, "", list0);
      Album album1 = album0.clone();
      assertEquals("'{{~{6'=rN", album1.getTitle());
      assertEquals("'{{~{6'=rN", album1.getArtist());
      assertEquals(6036, album1.getReleaseYear());
      assertEquals("", album1.getGenre());
      assertEquals(6036, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.previous((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.nextShuffle();
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.next((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.copySongs((List<Song>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album("multimedia=", "multimedia=", 39, "multimedia=", (List<Song>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Album album0 = new Album();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = album0.getCurrentSong();
      linkedList0.add(song0);
      album0.copySongs(linkedList0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Album album0 = new Album();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      album0.copySongs(linkedList0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      Album album0 = new Album("Lr1&IGllgxq8qH,~J';", "org.spotifumtp37.model.subscription.PremiumTop", 125, "multimedia=", list0);
      String string0 = album0.getGenre();
      assertEquals("org.spotifumtp37.model.subscription.PremiumTop", album0.getArtist());
      assertEquals("multimedia=", string0);
      assertEquals(125, album0.getReleaseYear());
      assertEquals("Lr1&IGllgxq8qH,~J';", album0.getTitle());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Album album0 = new Album();
      int int0 = album0.getReleaseYear();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Album album0 = null;
      try {
        album0 = new Album((Album) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Album album0 = new Album();
      album0.getSongs();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Album album0 = new Album();
      album0.getArtist();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Album album0 = new Album();
      album0.getTitle();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      PremiumTop premiumTop0 = new PremiumTop();
      user0.updatePremiumTop(premiumTop0);
      // Undeclared exception!
      try { 
        album0.previous(user0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("multimedia=", "multimedia=", (-2490), "multimedia=", linkedList0);
      User user0 = new User();
      try { 
        album0.previous(user0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Your subscription does not allow going back in the playlist.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song("+|fkY[*+7j}),$*", "+|fkY[*+7j}),$*", ", artist='", ", artist='", "$!X#", "", (-2490));
      linkedList0.add(song0);
      Album album0 = new Album("multimedia=", "multimedia=", (-2490), "multimedia=", linkedList0);
      album0.nextShuffle();
      assertEquals((-2490), album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("-", "-", "-", "-", "-", 3186, false, false, "-");
      album0.addSong("8w9@|qE:]", "8w9@|qE:]", "-", "8w9@|qE:]", "-", 3186, false, false, "-");
      album0.nextShuffle();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("-", "-", "-", "-", "-", 3186, false, false, "-");
      album0.addSong("8w9@|qE:]", "8w9@|qE:]", "-", "8w9@|qE:]", "-", 3186, false, false, "-");
      User user0 = new User();
      album0.next(user0);
      // Undeclared exception!
      album0.nextShuffle();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("-", "-", "-", "-", "-", 3186, false, false, "-");
      album0.setCurrentSong();
      album0.addSong("8w9@|qE:]", "8w9@|qE:]", "-", "8w9@|qE:]", "-", 3186, false, false, "-");
      User user0 = new User();
      // Undeclared exception!
      album0.next(user0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("-", "-", "-", "-", "-", 3186, false, false, "-");
      User user0 = new User();
      album0.next(user0);
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Album album0 = new Album();
      User user0 = new User();
      PremiumTop premiumTop0 = new PremiumTop();
      user0.updatePremiumTop(premiumTop0);
      // Undeclared exception!
      try { 
        album0.next(user0);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("*", "*", "*", "*", "*", 3, true, true, "*");
      album0.getSongsCopy();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Album album0 = new Album();
      List<Song> list0 = album0.getSongsCopy();
      Album album1 = new Album("org.spotifumtp37.model.subscription.FreePlan", "^%kOA", (-139), "", list0);
      Album album2 = album1.clone();
      assertEquals(0, album0.getReleaseYear());
      assertEquals((-139), album1.getReleaseYear());
      assertEquals("org.spotifumtp37.model.subscription.FreePlan", album2.getTitle());
      assertEquals("", album2.getGenre());
      assertEquals((-139), album2.getReleaseYear());
      assertEquals("^%kOA", album2.getArtist());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("-", "-", "-", "-", "-", 125, false, false, "-");
      // Undeclared exception!
      try { 
        album0.addSong("-", "-", "-", "-", "-", 125, false, false, "-");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // A song with the same name already exists in the album.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong("*", "*", "*", "*", "*", (-19), false, false, "*");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song duration must be positive.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong("", "", "", "", "", (-55), false, false, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song name cannot be null or empty.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.addSong((String) null, "", "A song with the same name already exists in the album.", "", "z}aD4m0~;x7V)wC", 3186, true, false, "O2|\"<-@;");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Song name cannot be null or empty.
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Album album0 = new Album();
      album0.addSong("-", ", email='", "-", "-", "OR0*8 E(\";y JUJ4U8", 3186, true, true, ", email='");
      Album album1 = album0.clone();
      assertEquals(0, album1.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Album album0 = new Album();
      Song song0 = new Song("song name cannot be null or empty.", "song name cannot be null or empty.", "song name cannot be null or empty.", "song name cannot be null or empty.", "song name cannot be null or empty.", "song name cannot be null or empty.", (-12));
      album0.setCurrentSong(song0);
      album0.getCurrentSong();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.setCurrentSong();
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Album album0 = new Album();
      // Undeclared exception!
      try { 
        album0.play((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Album", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Album album0 = new Album();
      album0.setTitle("-");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Album album0 = new Album();
      album0.deleteSong("*");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Album album0 = new Album();
      album0.setGenre(", email='");
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("multimedia=", "multimedia=", (-2490), "multimedia=", linkedList0);
      String string0 = album0.toString();
      assertEquals("Album{title='multimedia=', artist='multimedia=', releaseYear=-2490, genre='multimedia=', songs=[], currentSong=Song{name='', artist='', publisher='', lyrics='', musicalNotes='', genre='', durationInSeconds=0, timesPlayed=0}}", string0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      Album album0 = new Album();
      album0.getTotalDuration();
      assertEquals(0, album0.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("multimedia=", "multimedia=", (-2490), "multimedia=", linkedList0);
      album0.setReleaseYear((-2490));
      assertEquals((-2490), album0.getReleaseYear());
  }
}
