/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 19 15:33:50 GMT 2026
 */

package org.spotifumtp37.model.album;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Song_ESTest extends Song_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Song song0 = new Song("", "", "", "", "", "", 0);
      song0.setDurationInSeconds(39);
      song0.hashCode();
      assertEquals(39, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Song song0 = new Song(", artist='", ", artist='", ", artist='", "", "", ", artist='", 0);
      song0.hashCode();
      assertEquals(", artist='", song0.getGenre());
      assertEquals(", artist='", song0.getArtist());
      assertEquals("", song0.getMusicalNotes());
      assertEquals(", artist='", song0.getName());
      assertEquals("", song0.getLyrics());
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(", artist='", song0.getPublisher());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Song song0 = new Song();
      Song song1 = song0.clone();
      song1.setDurationInSeconds((-3164));
      boolean boolean0 = song0.equals(song1);
      assertEquals((-3164), song1.getDurationInSeconds());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Song song0 = new Song("", "nGPLf}tF5%4/;&MAFHH", "", "nGPLf}tF5%4/;&MAFHH", "nGPLf}tF5%4/;&MAFHH", "nGPLf}tF5%4/;&MAFHH", (-1));
      song0.setTimesPlayed(163);
      int int0 = song0.getTimesPlayed();
      assertEquals(163, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Song song0 = new Song(", artist='", ", artist='", ", artist='", "", "", ", artist='", 0);
      song0.setTimesPlayed((-1));
      int int0 = song0.getTimesPlayed();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Song song0 = new Song();
      song0.setPublisher((String) null);
      song0.getPublisher();
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Song song0 = new Song();
      song0.setPublisher("Song{name='', artist='', publisher='', lyrics='', musicalNotes=', genre='', genre='', durationInSeconds=0, timesPlayed=0}");
      song0.getPublisher();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Song song0 = new Song("!`E!QZg$Bu5", "nGPLf}tF5%4/;&MAFHH", "!`E!QZg$Bu5", "nGPLf}tF5%4/;&MAFHH", "nGPLf}tF5%4/;&MAFHH", "nGPLf}tF5%4/;&MAFHH", (-1));
      assertEquals("!`E!QZg$Bu5", song0.getName());
      
      song0.setName((String) null);
      song0.getName();
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getLyrics());
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getMusicalNotes());
      assertEquals("!`E!QZg$Bu5", song0.getPublisher());
      assertEquals((-1), song0.getDurationInSeconds());
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getGenre());
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getArtist());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Song song0 = new Song("K", "", (String) null, "R0", "R0", (String) null, 0);
      String string0 = song0.getName();
      assertEquals("", song0.getArtist());
      assertEquals(0, song0.getTimesPlayed());
      assertNotNull(string0);
      assertEquals("K", string0);
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals("R0", song0.getMusicalNotes());
      assertEquals("R0", song0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Song song0 = new Song("NnRj7_ )4o~", (String) null, "]", "org.spotifumtp37.model.album.Song", "org.spotifumtp37.model.album.Song", "", 1776);
      String string0 = song0.getMusicalNotes();
      assertNotNull(string0);
      assertEquals("]", song0.getPublisher());
      assertEquals("", song0.getGenre());
      assertEquals("org.spotifumtp37.model.album.Song", string0);
      assertEquals(0, song0.getTimesPlayed());
      assertEquals("NnRj7_ )4o~", song0.getName());
      assertEquals(1776, song0.getDurationInSeconds());
      assertEquals("org.spotifumtp37.model.album.Song", song0.getLyrics());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Song song0 = new Song();
      song0.setLyrics((String) null);
      song0.getLyrics();
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Song song0 = new Song();
      song0.setLyrics("nU,o~$r)SM='L-");
      song0.getLyrics();
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Song song0 = new Song();
      song0.setGenre((String) null);
      song0.getGenre();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Song song0 = new Song(", artist='", ", artist='", ", artist='", "", "", ", artist='", 0);
      String string0 = song0.getGenre();
      assertEquals(", artist='", string0);
      assertEquals(", artist='", song0.getName());
      assertEquals("", song0.getLyrics());
      assertEquals("", song0.getMusicalNotes());
      assertEquals(", artist='", song0.getArtist());
      assertEquals(", artist='", song0.getPublisher());
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Song song0 = new Song("", "", "", "", "", "", 0);
      assertEquals(0, song0.getDurationInSeconds());
      
      song0.setDurationInSeconds(1);
      int int0 = song0.getDurationInSeconds();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Song song0 = new Song("", "", "", "", "", "", (-1));
      int int0 = song0.getDurationInSeconds();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Song song0 = new Song();
      song0.setArtist((String) null);
      song0.getArtist();
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Song song0 = new Song();
      song0.setArtist("Song{name='");
      song0.getArtist();
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Song song0 = new Song();
      song0.setTimesPlayed((-1981));
      song0.clone();
      assertEquals((-1981), song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Song song0 = new Song("", "", "", "", "", "", (-1));
      Song song1 = song0.clone();
      assertTrue(song1.equals((Object)song0));
      assertEquals((-1), song1.getDurationInSeconds());
      assertEquals(0, song1.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Song song0 = new Song();
      song0.setName((String) null);
      // Undeclared exception!
      try { 
        song0.hashCode();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Song", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Song song0 = null;
      try {
        song0 = new Song((Song) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.album.Song", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Song song0 = new Song();
      song0.getName();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Song song0 = new Song();
      song0.getPublisher();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Song song0 = new Song();
      song0.getGenre();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Song song0 = new Song();
      song0.getMusicalNotes();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Song song0 = new Song("", "", "", "", "", "", (-1));
      int int0 = song0.getTimesPlayed();
      assertEquals(0, int0);
      assertEquals((-1), song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Song song0 = new Song();
      song0.getLyrics();
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Song song0 = new Song("", "", "", "", "", "", 0);
      int int0 = song0.getDurationInSeconds();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Song song0 = new Song();
      song0.getArtist();
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Song song0 = new Song();
      Song song1 = song0.clone();
      song1.incrementTimesPlayed();
      boolean boolean0 = song1.equals(song0);
      assertEquals(1, song1.getTimesPlayed());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Song song0 = new Song();
      Song song1 = new Song(song0);
      assertTrue(song1.equals((Object)song0));
      
      song0.setGenre((String) null);
      boolean boolean0 = song0.equals(song1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Song song0 = new Song();
      Song song1 = new Song();
      assertTrue(song1.equals((Object)song0));
      
      song1.setMusicalNotes("4h5Yq\"");
      boolean boolean0 = song0.equals(song1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Song song0 = new Song("", "", "", "", "", "", 0);
      Song song1 = new Song();
      assertTrue(song1.equals((Object)song0));
      
      song1.setLyrics(":zJXMf/vObJO");
      boolean boolean0 = song1.equals(song0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Song song0 = new Song();
      Song song1 = new Song("", "", "", "", "", "", 2938);
      boolean boolean0 = song0.equals(song1);
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song1.getTimesPlayed());
      assertFalse(boolean0);
      assertEquals(2938, song1.getDurationInSeconds());
      assertFalse(song1.equals((Object)song0));
      assertEquals(0, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Song song0 = new Song();
      song0.setPublisher("PXjM2)YMwC{SsM4D=");
      Song song1 = new Song();
      boolean boolean0 = song0.equals(song1);
      assertEquals(0, song1.getDurationInSeconds());
      assertFalse(boolean0);
      assertEquals(0, song1.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Song song0 = new Song();
      song0.setArtist("*e(");
      Song song1 = new Song();
      boolean boolean0 = song0.equals(song1);
      assertFalse(boolean0);
      assertEquals(0, song1.getTimesPlayed());
      assertEquals(0, song1.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Song song0 = new Song("K", "", (String) null, "R0", "R0", (String) null, 0);
      Song song1 = new Song();
      boolean boolean0 = song0.equals(song1);
      assertEquals("", song0.getArtist());
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song1.getDurationInSeconds());
      assertEquals("R0", song0.getMusicalNotes());
      assertEquals("K", song0.getName());
      assertEquals("R0", song0.getLyrics());
      assertEquals(0, song1.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Song song0 = new Song("!`E!QZg$Bu5", "nGPLf}tF5%4/;&MAFHH", "!`E!QZg$Bu5", "nGPLf}tF5%4/;&MAFHH", "nGPLf}tF5%4/;&MAFHH", "nGPLf}tF5%4/;&MAFHH", (-1));
      boolean boolean0 = song0.equals("!`E!QZg$Bu5");
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getGenre());
      assertEquals(0, song0.getTimesPlayed());
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getArtist());
      assertEquals("!`E!QZg$Bu5", song0.getName());
      assertFalse(boolean0);
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getLyrics());
      assertEquals("!`E!QZg$Bu5", song0.getPublisher());
      assertEquals((-1), song0.getDurationInSeconds());
      assertEquals("nGPLf}tF5%4/;&MAFHH", song0.getMusicalNotes());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Song song0 = new Song();
      boolean boolean0 = song0.equals((Object) null);
      assertEquals(0, song0.getTimesPlayed());
      assertEquals(0, song0.getDurationInSeconds());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Song song0 = new Song();
      boolean boolean0 = song0.equals(song0);
      assertTrue(boolean0);
      assertEquals(0, song0.getDurationInSeconds());
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Song song0 = new Song();
      Song song1 = song0.clone();
      boolean boolean0 = song1.equals(song0);
      assertTrue(boolean0);
      assertEquals(0, song1.getDurationInSeconds());
      assertEquals(0, song1.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Song song0 = new Song("9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "dr", "9>3Bd63?%`di(+", "L+C^ZnZ8|r T&", 1542);
      String string0 = song0.toString();
      assertEquals("Song{name='9>3Bd63?%`di(+', artist='9>3Bd63?%`di(+', publisher='9>3Bd63?%`di(+', lyrics='dr', musicalNotes='9>3Bd63?%`di(+', genre='L+C^ZnZ8|r T&', durationInSeconds=1542, timesPlayed=0}", string0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Song song0 = new Song("9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "dr", "9>3Bd63?%`di(+", "L+C^ZnZ8|r T&", 1542);
      assertEquals("9>3Bd63?%`di(+", song0.getMusicalNotes());
      
      song0.setMusicalNotes((String) null);
      song0.getMusicalNotes();
      assertEquals("9>3Bd63?%`di(+", song0.getPublisher());
      assertEquals("dr", song0.getLyrics());
      assertEquals(0, song0.getTimesPlayed());
      assertEquals("L+C^ZnZ8|r T&", song0.getGenre());
      assertEquals("9>3Bd63?%`di(+", song0.getName());
      assertEquals(1542, song0.getDurationInSeconds());
      assertEquals("9>3Bd63?%`di(+", song0.getArtist());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Song song0 = new Song("9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "dr", "9>3Bd63?%`di(+", "L+C^ZnZ8|r T&", 1542);
      boolean boolean0 = song0.isMultimedia();
      assertEquals("dr", song0.getLyrics());
      assertFalse(boolean0);
      assertEquals("9>3Bd63?%`di(+", song0.getArtist());
      assertEquals(1542, song0.getDurationInSeconds());
      assertEquals("9>3Bd63?%`di(+", song0.getPublisher());
      assertEquals("9>3Bd63?%`di(+", song0.getName());
      assertEquals("9>3Bd63?%`di(+", song0.getMusicalNotes());
      assertEquals(0, song0.getTimesPlayed());
      assertEquals("L+C^ZnZ8|r T&", song0.getGenre());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Song song0 = new Song("9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "dr", "9>3Bd63?%`di(+", "L+C^ZnZ8|r T&", 1542);
      song0.setTimesPlayed(1542);
      song0.clone();
      assertEquals(1542, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Song song0 = new Song("9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "9>3Bd63?%`di(+", "dr", "9>3Bd63?%`di(+", "L+C^ZnZ8|r T&", 1542);
      boolean boolean0 = song0.isExplicit();
      assertEquals("9>3Bd63?%`di(+", song0.getMusicalNotes());
      assertEquals("L+C^ZnZ8|r T&", song0.getGenre());
      assertEquals("9>3Bd63?%`di(+", song0.getName());
      assertEquals(0, song0.getTimesPlayed());
      assertFalse(boolean0);
      assertEquals("9>3Bd63?%`di(+", song0.getPublisher());
      assertEquals("dr", song0.getLyrics());
      assertEquals(1542, song0.getDurationInSeconds());
      assertEquals("9>3Bd63?%`di(+", song0.getArtist());
  }
}
