/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 20 10:41:58 GMT 2026
 */

package org.spotifumtp37.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZoneOffset;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.function.BiFunction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.time.MockLocalDateTime;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.Album;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.model.playlist.Playlist;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.user.History;
import org.spotifumtp37.model.user.User;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Stats_ESTest extends Stats_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      User user0 = new User();
      Playlist playlist0 = new Playlist(user0, "org.spotifumtp37.util.Stats", "org.spotifumtp37.util.Stats", (-2065), ")f(D$c_R5qRY2!@~", (List<Song>) null);
      hashMap0.put("org.spotifumtp37.util.Stats", playlist0);
      User user1 = Stats.userWithMostPlaylists(hashMap0);
      assertEquals(0.0, user1.getPontos(), 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      PremiumBase premiumBase0 = new PremiumBase();
      List<History> list0 = user0.getHistory();
      User user1 = new User("", (String) null, ", subscription plan=", premiumBase0, "", 5.0, list0);
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user1, "ubSs2cXt", ", subscription plan=", (-1719), "B]ct ", linkedList0);
      hashMap0.put("", playlist0);
      User user2 = Stats.userWithMostPlaylists(hashMap0);
      assertSame(user2, user1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      Song song0 = new Song("|vaWyGps", "|vaWyGps", "|vaWyGps", "e/vclHrYaxxqx+nW}", "", "|vaWyGps", 1);
      user0.updateHistory(song0);
      hashMap0.put("6l.", user0);
      String string0 = Stats.mostListenedGenre(hashMap0);
      assertEquals("|vaWyGps", string0);
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      User user0 = new User();
      Album album0 = new Album();
      Song song0 = album0.getCurrentSong();
      user0.updateHistory(song0);
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("b", user0);
      String string0 = Stats.mostListenedGenre(hashMap0);
      assertNotNull(string0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("", user0);
      Album album0 = new Album();
      album0.play(user0);
      User user1 = Stats.getUserWithMostPoints(hashMap0);
      assertSame(user1, user0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      PremiumBase premiumBase0 = new PremiumBase();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("s:<v", "s:<v", "s:<v", premiumBase0, "", (-371.904), linkedList0);
      BiFunction<Object, Object, User> biFunction0 = (BiFunction<Object, Object, User>) mock(BiFunction.class, new ViolatedAssumptionAnswer());
      doReturn(user0).when(biFunction0).apply(any() , any());
      hashMap0.compute("s:<v", biFunction0);
      User user1 = Stats.getUserWithMostPoints(hashMap0);
      assertEquals("s:<v", user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      user0.setPontos((-884.0));
      hashMap0.put("", user0);
      ZoneId zoneId0 = ZoneId.systemDefault();
      LocalDateTime localDateTime0 = MockLocalDateTime.now(zoneId0);
      User user1 = Stats.getTopListenerFromDate(hashMap0, localDateTime0);
      assertEquals("", user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("", user0);
      Album album0 = new Album();
      album0.play(user0);
      User user1 = Stats.getTopListener(hashMap0);
      assertEquals("", user1.getPassword());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      LinkedList<History> linkedList0 = new LinkedList<History>();
      PremiumBase premiumBase0 = new PremiumBase();
      User user0 = new User("b`F4", "^", (String) null, premiumBase0, "^", (-1.0), linkedList0);
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("rBTu`pdPYKh~E", user0);
      User user1 = Stats.getTopListener(hashMap0);
      assertNull(user1.getAddress());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenrePlaylistWithinTime(hashMap0, 2147483645);
      Album album0 = new Album("", "", 2147483645, "org.spotifumtp37.util.Stats", list0);
      album0.addSong("org.spotifumtp37.util.Stats", "org.spotifumtp37.util.Stats", "org.spotifumtp37.util.Stats", "org.spotifumtp37.util.Stats", "", 39, false, true, (String) null);
      hashMap0.put("org.spotifumtp37.util.Stats", album0);
      Song song0 = Stats.getMostPlayedSong(hashMap0);
      assertEquals(0, song0.getTimesPlayed());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song();
      linkedList0.add(song0);
      Album album0 = new Album("GSx", "GSx", 350, "GSx", linkedList0);
      hashMap0.put("GSx", album0);
      Song song1 = Stats.getMostPlayedSong(hashMap0);
      assertEquals("", song1.getPublisher());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Album album0 = new Album();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      album0.addSong("|]l/IX;N#", "|]l/IX;N#", "", (String) null, "|]l/IX;N#", 2147483645, true, true, "");
      hashMap0.put("", album0);
      Song song0 = Stats.getMostPlayedSong(hashMap0);
      assertEquals(2147483645, song0.getDurationInSeconds());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("", "R", 2147483645, "p", linkedList0);
      album0.addSong("R", "p<=", "", "", "", 2147483645, true, false, ")HnHz9K`^&h BeZ+}");
      hashMap0.put((String) null, album0);
      Stats.getMostListenedArtist(hashMap0);
      assertEquals(1, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "public", "public", 1, "public", linkedList0);
      hashMap0.put("public", playlist0);
      long long0 = Stats.countPublicPlaylists(hashMap0);
      assertEquals(1L, long0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      hashMap0.put("", (Playlist) null);
      // Undeclared exception!
      try { 
        Stats.userWithMostPlaylists(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("zTk]-5S!Z3\"w", (User) null);
      // Undeclared exception!
      try { 
        Stats.mostListenedGenre(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("|]l/IX;N#", (User) null);
      // Undeclared exception!
      try { 
        Stats.getUserWithMostPoints(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("", (User) null);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      // Undeclared exception!
      try { 
        Stats.getTopListenerFromDate(hashMap0, localDateTime0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put("At|Hwl", (User) null);
      // Undeclared exception!
      try { 
        Stats.getTopListener(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      hashMap0.put("", (Album) null);
      // Undeclared exception!
      try { 
        Stats.getMostPlayedSong(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      hashMap0.put("", (Album) null);
      // Undeclared exception!
      try { 
        Stats.getMostListenedArtist(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.util.Stats", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      hashMap0.put("", (Playlist) null);
      // Undeclared exception!
      try { 
        Stats.countPublicPlaylists(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.stream.ReferencePipeline$2$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "Song duration must be positive.", "null", (-1), "Song duration must be positive.", linkedList0);
      hashMap0.put("Song duration must be positive.", playlist0);
      User user0 = Stats.userWithMostPlaylists(hashMap0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      LinkedList<History> linkedList0 = new LinkedList<History>();
      PremiumBase premiumBase0 = new PremiumBase();
      User user0 = new User("b`F4", "^", (String) null, premiumBase0, "^", (-1.0), linkedList0);
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      LinkedList<Song> linkedList1 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "^", "eOIl8ms!", 39, (String) null, linkedList1);
      hashMap0.put("tH6m!zsWu{8$|-*\"gP", playlist0);
      User user1 = Stats.userWithMostPlaylists(hashMap0);
      assertEquals("^", user1.getPassword());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      User user0 = Stats.userWithMostPlaylists(hashMap0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      User user0 = Stats.userWithMostPlaylists((Map<String, Playlist>) null);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      HashMap<String, Playlist> hashMap1 = new HashMap<String, Playlist>();
      Playlist playlist0 = new Playlist((User) null, "org.spotifumtp37.model.subscription.PremiumBase", "|]l/IX;N#", 2147483645, "", list0);
      hashMap1.put("|]l/IX;N#", playlist0);
      long long0 = Stats.countPublicPlaylists(hashMap1);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      long long0 = Stats.countPublicPlaylists(hashMap0);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      long long0 = Stats.countPublicPlaylists((Map<String, Playlist>) null);
      assertEquals(0L, long0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("private", user0);
      String string0 = Stats.mostListenedGenre(hashMap0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      String string0 = Stats.mostListenedGenre(hashMap0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      String string0 = Stats.mostListenedGenre((Map<String, User>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("", user0);
      User user1 = Stats.getUserWithMostPoints(hashMap0);
      assertSame(user1, user0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = Stats.getUserWithMostPoints(hashMap0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      User user0 = Stats.getUserWithMostPoints((Map<String, User>) null);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("", user0);
      Album album0 = new Album();
      album0.play(user0);
      hashMap0.put((String) null, user0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      User user1 = Stats.getTopListenerFromDate(hashMap0, localDateTime0);
      assertEquals("", user1.getEmail());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("!hwe4tz]]N", user0);
      User user1 = Stats.getTopListenerFromDate(hashMap0, (LocalDateTime) null);
      assertNull(user1);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("", user0);
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      User user1 = Stats.getTopListenerFromDate(hashMap0, localDateTime0);
      assertEquals("", user1.getName());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      LocalDateTime localDateTime0 = MockLocalDateTime.now();
      User user0 = Stats.getTopListenerFromDate(hashMap0, localDateTime0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      ZoneOffset zoneOffset0 = ZoneOffset.MIN;
      LocalDateTime localDateTime0 = MockLocalDateTime.now((ZoneId) zoneOffset0);
      User user0 = Stats.getTopListenerFromDate((Map<String, User>) null, localDateTime0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put("", user0);
      User user1 = Stats.getTopListener(hashMap0);
      assertSame(user1, user0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = Stats.getTopListener(hashMap0);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      User user0 = Stats.getTopListener((Map<String, User>) null);
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Album album0 = new Album();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      album0.addSong("|]l/IX;N#", "|]l/IX;N#", "", (String) null, "|]l/IX;N#", 2147483645, true, true, "");
      hashMap0.put("", album0);
      String string0 = Stats.getMostListenedArtist(hashMap0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Album album0 = new Album();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      hashMap0.put("", album0);
      String string0 = Stats.getMostListenedArtist(hashMap0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      String string0 = Stats.getMostListenedArtist(hashMap0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      String string0 = Stats.getMostListenedArtist((Map<String, Album>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Album album0 = new Album();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      hashMap0.put("", album0);
      Song song0 = Stats.getMostPlayedSong(hashMap0);
      assertNull(song0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Song song0 = Stats.getMostPlayedSong(hashMap0);
      assertNull(song0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Song song0 = Stats.getMostPlayedSong((Map<String, Album>) null);
      assertNull(song0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Stats stats0 = new Stats();
  }
}
