/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 20 10:39:20 GMT 2026
 */

package org.spotifumtp37.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.spotifumtp37.model.album.Album;
import org.spotifumtp37.model.album.MultimediaSong;
import org.spotifumtp37.model.album.Song;
import org.spotifumtp37.model.playlist.Playlist;
import org.spotifumtp37.model.subscription.FreePlan;
import org.spotifumtp37.model.subscription.PremiumBase;
import org.spotifumtp37.model.subscription.PremiumTop;
import org.spotifumtp37.model.user.History;
import org.spotifumtp37.model.user.User;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SpotifUMData_ESTest extends SpotifUMData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      spotifUMData0.addUser(user0);
      User user1 = spotifUMData0.getUser("");
      assertEquals("", user1.getName());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("4 :LzA]jF;]M^/Kt", "4 :LzA]jF;]M^/Kt", 506, "4 :LzA]jF;]M^/Kt", linkedList0);
      album0.addSong("4 :LzA]jF;]M^/Kt", "4 :LzA]jF;]M^/Kt", "4 :LzA]jF;]M^/Kt", "4 :LzA]jF;]M^/Kt", "4 :LzA]jF;]M^/Kt", 506, false, true, "S\"%Ol#R.ZsOl5g");
      spotifUMData0.addAlbum(album0);
      MultimediaSong multimediaSong0 = (MultimediaSong)spotifUMData0.getSong("4 :LzA]jF;]M^/Kt", "4 :LzA]jF;]M^/Kt");
      assertEquals("S\"%Ol#R.ZsOl5g", multimediaSong0.getVideoLink());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 506, "4 :LzA]&F;]M^/Kt", linkedList0);
      album0.addSong("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 506, false, false, "4 :LzA]&F;]M^/Kt");
      spotifUMData0.addAlbum(album0);
      Song song0 = spotifUMData0.getSong("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt");
      assertEquals("4 :LzA]&F;]M^/Kt", song0.getGenre());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "%1M*RJr RJ", "Albums: ", (-2075900857), "org.spotifumtp37.model.subscription.PremiumBase", linkedList0);
      SpotifUMData spotifUMData0 = new SpotifUMData();
      spotifUMData0.addPlaylist(playlist0);
      Map<String, Playlist> map0 = spotifUMData0.getPlaylistMapByCreator(user0);
      spotifUMData0.setMapPlaylists(map0);
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "\n+Daylistc: ", "\n+Daylistc: ", 5, "\n+Daylistc: ", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      Playlist playlist1 = spotifUMData0.getPlaylist("\n+Daylistc: ");
      assertEquals("\n+Daylistc: ", playlist1.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>(425);
      List<Song> list0 = user0.createTopGenreExplicitPlaylist(hashMap0);
      Playlist playlist0 = new Playlist(user0, "?S^", "?S^", (-1), "\nUsers: ", list0);
      spotifUMData0.addPlaylist(playlist0);
      Playlist playlist1 = spotifUMData0.getPlaylist("?S^");
      assertEquals("?S^", playlist1.getPlaylistName());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      Map<String, Album> map0 = spotifUMData0.getMapAlbums();
      assertEquals(1, map0.size());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      spotifUMData0.addUser(user0);
      User user1 = spotifUMData0.getCurrentUserPointer("");
      assertNotSame(user1, user0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      FreePlan freePlan0 = new FreePlan();
      User user0 = new User();
      List<History> list0 = user0.getHistory();
      User user1 = new User("a)/@T}quR<|", "+Czlt<((HM3/-FpL+", "+Czlt<((HM3/-FpL+", freePlan0, "W<|dCHucC*YAO", 2322.600312951133, list0);
      spotifUMData0.addUser(user1);
      User user2 = spotifUMData0.getCurrentUserPointer("a)/@T}quR<|");
      assertNotSame(user2, user1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      PremiumTop premiumTop0 = new PremiumTop();
      User user0 = new User();
      List<History> list0 = user0.getHistory();
      User user1 = new User("$", "$", "S\"%Ol#R.ZsOl5g", premiumTop0, ", history=", (-3038.8779744337203), list0);
      spotifUMData0.addUser(user1);
      User user2 = spotifUMData0.getCurrentUserPointer("$");
      assertNotSame(user2, user0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "\n+Daylistc: ", "\n+Daylistc: ", 5, "\n+Daylistc: ", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      Playlist playlist1 = spotifUMData0.getAnyPlaylist("\n+Daylistc: ", user0);
      assertEquals(5, playlist1.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "hLN>&ZE0`X_Pd-", "public", (-2049870753), "public", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      Playlist playlist1 = spotifUMData0.getAnyPlaylist("hLN>&ZE0`X_Pd-", user0);
      assertEquals("public", playlist1.getPlaylistDescription());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      Album album1 = spotifUMData0.getAlbum("");
      assertEquals("", album1.getGenre());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      List<Song> list0 = album0.getSongs();
      Album album1 = new Album((String) null, "o)d7d^:Aq{kZ-> ", (-646), "", list0);
      spotifUMData0.addAlbum(album1);
      Album album2 = spotifUMData0.getAlbum((String) null);
      assertEquals((-646), album2.getReleaseYear());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      // Undeclared exception!
      try { 
        spotifUMData0.setMapAlbums((Map<String, Album>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "org.spotifumtp37.model.SpotifUMData", "org.spotifumtp37.model.SpotifUMData", (-1916582713), "org.spotifumtp37.model.SpotifUMData", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      // Undeclared exception!
      try { 
        spotifUMData0.getPlaylistMapByCreator((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist((User) null, "org.spotifumtp37.model.SpotifUMData", "org.spotifumtp37.model.SpotifUMData", (-1916582713), "org.spotifumtp37.model.SpotifUMData", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      // Undeclared exception!
      try { 
        spotifUMData0.getAnyPlaylist("org.spotifumtp37.model.SpotifUMData", (User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      // Undeclared exception!
      try { 
        spotifUMData0.addUser((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      // Undeclared exception!
      try { 
        spotifUMData0.addPlaylist((Playlist) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      // Undeclared exception!
      try { 
        spotifUMData0.addAlbum((Album) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      SpotifUMData spotifUMData0 = null;
      try {
        spotifUMData0 = new SpotifUMData((SpotifUMData) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      FreePlan freePlan0 = new FreePlan();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("j", "j", "j", freePlan0, "VYg", 2462.976216397, linkedList0);
      spotifUMData0.addUser(user0);
      boolean boolean0 = spotifUMData0.existsUser("j");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      boolean boolean0 = spotifUMData0.existsPlaylist("a(Y=~RPf/7t0}T\"d+");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "\n+Daylistc: ", "\n+Daylistc: ", 5, "\n+Daylistc: ", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      boolean boolean0 = spotifUMData0.existsPlaylist("\n+Daylistc: ");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 506, "4 :LzA]&F;]M^/Kt", linkedList0);
      album0.addSong("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 506, false, false, "j#kE-(|$]sE");
      spotifUMData0.addAlbum(album0);
      boolean boolean0 = spotifUMData0.existsSong("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 506, "4 :LzA]&F;]M^/Kt", linkedList0);
      album0.addSong("t5)5]$2", "t5)5]$2", "j#kE-(|$]sE", "4 :LzA]&F;]M^/Kt", "t5)5]$2", 506, false, false, "wb");
      spotifUMData0.addAlbum(album0);
      boolean boolean0 = spotifUMData0.existsSong("S\"%Ol#R.ZsOl5g", "4 :LzA]&F;]M^/Kt");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      boolean boolean0 = spotifUMData0.existsAlbum("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      boolean boolean0 = spotifUMData0.existsAlbum("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      User user0 = new User();
      hashMap0.put(", playlistDescription='", user0);
      spotifUMData0.setMapUsers(hashMap0);
      SpotifUMData spotifUMData1 = new SpotifUMData(spotifUMData0);
      assertTrue(spotifUMData1.equals((Object)spotifUMData0));
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      spotifUMData0.addUser(user0);
      spotifUMData0.removeUser("");
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      try { 
        spotifUMData0.removeUser(",YTk)");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // ,YTk)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "\nPlaylists: ", "\nPlaylists: ", 31, "\nPlaylists: ", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      spotifUMData0.removePlaylist("\nPlaylists: ");
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      try { 
        spotifUMData0.removePlaylist(", status='");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // , status='
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      spotifUMData0.removeAlbum("");
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      try { 
        spotifUMData0.removeAlbum((String) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      spotifUMData0.addUser(user0);
      try { 
        spotifUMData0.addUser(user0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "\n+Daylistc: ", "\n+Daylistc: ", (-22), "\n+Daylistc: ", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      try { 
        spotifUMData0.addPlaylist(playlist0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // +Daylistc: 
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      try { 
        spotifUMData0.addAlbum(album0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      try { 
        spotifUMData0.getUser("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "\n+Daylistc: ", "\n+Daylistc: ", 18, "\n+Daylistc: ", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      try { 
        spotifUMData0.getAnyPlaylist("\n+Daylistc: ", (User) null);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // 
         // +Daylistc: 
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      try { 
        spotifUMData0.getPlaylist("Ef/JHN[Q`}!:");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // Ef/JHN[Q`}!:
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, (String) null, "org.spotifumtp37.model.SpotifUMData", 0, "\nDliC;;c$", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      Playlist playlist1 = spotifUMData0.getPlaylist((String) null);
      assertEquals(0, playlist1.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song("fd7BG>OJi", "fd7BG>OJi", "4 :LzA]&F;]M^/Kt", "\nPlaylists: ", "6,;0(b8", "\nPlaylists: ", 575);
      linkedList0.addLast(song0);
      Album album0 = new Album("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 575, "4 :LzA]&F;]M^/Kt", linkedList0);
      album0.addSong("t)5]$2", "t)5]$2", "t)5]$2", "4 :LzA]&F;]M^/Kt", "t)5]$2", 575, true, true, "4 :LzA]&F;]M^/Kt");
      spotifUMData0.addAlbum(album0);
      Song song1 = spotifUMData0.getSong("t)5]$2", "4 :LzA]&F;]M^/Kt");
      assertEquals("t)5]$2", song1.getLyrics());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      try { 
        spotifUMData0.getAlbum(", artist='");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // , artist='
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Album album0 = new Album("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 575, "4 :LzA]&F;]M^/Kt", linkedList0);
      spotifUMData0.addAlbum(album0);
      Album album1 = spotifUMData0.getAlbum("4 :LzA]&F;]M^/Kt");
      assertEquals("4 :LzA]&F;]M^/Kt", album1.getArtist());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      PremiumBase premiumBase0 = new PremiumBase();
      User user0 = new User();
      List<History> list0 = user0.getHistory();
      User user1 = new User("Your subscription does not allow adding songs to the playlist.", "N<9S\"rJH", "N<9S\"rJH", premiumBase0, ",YTk)", 476.7071159318805, list0);
      spotifUMData0.addUser(user1);
      User user2 = spotifUMData0.getUser("Your subscription does not allow adding songs to the playlist.");
      assertEquals("N<9S\"rJH", user2.getEmail());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      boolean boolean0 = spotifUMData0.existsUser("eRD}J,\"9");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      Album album0 = new Album();
      List<Song> list0 = album0.getSongsCopy();
      Playlist playlist0 = new Playlist(user0, "private", "private", 0, "private", list0);
      spotifUMData0.addPlaylist(playlist0);
      Playlist playlist1 = spotifUMData0.getAnyPlaylist("private", user0);
      assertEquals(0, playlist1.getNumberOfFollowers());
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      try { 
        spotifUMData0.getAnyPlaylist((String) null, user0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Song song0 = new Song("fd7BG>OJi", "fd7BG>OJi", "4 :LzA]&F;]M^/Kt", "\nPlaylists: ", "6,;0(b8", "\nPlaylists: ", 575);
      linkedList0.addLast(song0);
      Album album0 = new Album("4 :LzA]&F;]M^/Kt", "4 :LzA]&F;]M^/Kt", 575, "4 :LzA]&F;]M^/Kt", linkedList0);
      spotifUMData0.addAlbum(album0);
      try { 
        spotifUMData0.getSong("t)5]$2", "4 :LzA]&F;]M^/Kt");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // t)5]$2
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      boolean boolean0 = spotifUMData0.existsSong("Your subscription does not allow adding songs to the playlist.", "Your subscription does not allow adding songs to the playlist.");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      HashMap<String, Playlist> hashMap0 = new HashMap<String, Playlist>();
      hashMap0.put("k,Yq2G}]", (Playlist) null);
      // Undeclared exception!
      try { 
        spotifUMData0.setMapPlaylists(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      HashMap<String, User> hashMap0 = new HashMap<String, User>();
      hashMap0.put(", playlistDescription='", (User) null);
      // Undeclared exception!
      try { 
        spotifUMData0.setMapUsers(hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.spotifumtp37.model.SpotifUMData", e);
      }
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      HashMap<String, Album> hashMap0 = new HashMap<String, Album>();
      Album album0 = new Album();
      hashMap0.put("\nUsers: ", album0);
      spotifUMData0.setMapAlbums(hashMap0);
      assertEquals(1, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Map<String, Album> map0 = spotifUMData0.getMapAlbumsCopy();
      spotifUMData0.setMapAlbums(map0);
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      LinkedList<Song> linkedList0 = new LinkedList<Song>();
      Playlist playlist0 = new Playlist(user0, "0d7BG>OJi", "0d7BG>OJi", 0, "0d7BG>OJi", linkedList0);
      spotifUMData0.addPlaylist(playlist0);
      Map<String, Playlist> map0 = spotifUMData0.getMapPlaylists();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Map<String, Playlist> map0 = spotifUMData0.getMapPlaylists();
      spotifUMData0.setMapPlaylists(map0);
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      spotifUMData0.addUser(user0);
      Map<String, User> map0 = spotifUMData0.getMapUsers();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Map<String, User> map0 = spotifUMData0.getMapUsers();
      spotifUMData0.setMapUsers(map0);
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      Map<String, Album> map0 = spotifUMData0.getMapAlbumsCopy();
      assertFalse(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      FreePlan freePlan0 = new FreePlan();
      LinkedList<History> linkedList0 = new LinkedList<History>();
      User user0 = new User("qXX", "pmB?A", "\nUsers: ", freePlan0, "qXX", (-732.843491), linkedList0);
      Map<String, Album> map0 = spotifUMData0.getMapAlbumsCopy();
      List<Song> list0 = user0.createTopGenrePlaylist(map0);
      Playlist playlist0 = new Playlist(user0, "org.spotifumtp37.model.SpotifUMData", "?a", 2, "qXX", list0);
      spotifUMData0.addPlaylist(playlist0);
      SpotifUMData spotifUMData1 = new SpotifUMData();
      boolean boolean0 = spotifUMData1.equals(spotifUMData0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      spotifUMData0.addUser(user0);
      SpotifUMData spotifUMData1 = new SpotifUMData();
      boolean boolean0 = spotifUMData1.equals(spotifUMData0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      SpotifUMData spotifUMData1 = new SpotifUMData();
      boolean boolean0 = spotifUMData1.equals(spotifUMData0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      boolean boolean0 = spotifUMData0.equals("hh#,=$0g<{RfY0");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      boolean boolean0 = spotifUMData0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      boolean boolean0 = spotifUMData0.equals(spotifUMData0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      SpotifUMData spotifUMData1 = new SpotifUMData();
      boolean boolean0 = spotifUMData1.equals(spotifUMData0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      Album album0 = new Album();
      List<Song> list0 = album0.getSongsCopy();
      Playlist playlist0 = new Playlist(user0, "private", "private", 0, "private", list0);
      spotifUMData0.addPlaylist(playlist0);
      SpotifUMData spotifUMData1 = new SpotifUMData(spotifUMData0);
      assertTrue(spotifUMData1.equals((Object)spotifUMData0));
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      spotifUMData0.addUser(user0);
      SpotifUMData spotifUMData1 = spotifUMData0.clone();
      assertTrue(spotifUMData1.equals((Object)spotifUMData0));
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Album album0 = new Album();
      spotifUMData0.addAlbum(album0);
      SpotifUMData spotifUMData1 = new SpotifUMData(spotifUMData0);
      assertFalse(spotifUMData1.equals((Object)spotifUMData0));
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      Map<String, Album> map0 = spotifUMData0.getMapAlbums();
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      String string0 = spotifUMData0.toString();
      assertEquals("Albums: {}\nUsers: {}\nPlaylists: {}", string0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = spotifUMData0.getCurrentUserPointer("pP@XIr$(?,");
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      SpotifUMData spotifUMData0 = new SpotifUMData();
      User user0 = new User();
      Map<String, Playlist> map0 = spotifUMData0.getPlaylistMapByCreator(user0);
      assertTrue(map0.isEmpty());
  }
}
